[package]
name = "rust-mongodb-atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.2"  # MongoDB Rust driver
tokio = { version = "1", features = ["full"] }  # Async runtime
serde = { version = "1", features = ["derive"] } # Serialization
dotenvy = "0.15"  # Load .env file