[package]
name = "sqlite-sqlx-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = {version="0.8.3", features=["runtime-tokio","tls-rustls", "sqlite","time"]}
# sqlx is an asynchronous library
tokio={version="1.0", features=["full"]}
# sqlx will read .env file
dotenv ="0.15"


