[workspace]
members = [
  "_Libraries\\serde\\serde_demo",
  "#Lifetime\\lifetime_demo",
  "#Concurrency\\semaphore_demo",
  "#File\\file_demo",
  "#Unsafe\\unsafe-demo",
  "#String\\string-demo", 
  "#Regex/regex_demo", 
  "Projects/minesweeper", "#Test/testlib", "Projects/minesweeper_exercism", "Projects/minesweeper_gui"]

resolver = "2"
