edition = "2021"
tab_spaces = 2
max_width = 100  # Increase max line width (default is 100)
wrap_comments = false  # Avoid breaking comments into multiple lines
reorder_imports = true  # Organize imports