[package]
name = "rust-firebase-basic"
version = "0.1.0"
edition = "2021"

[dependencies]
firebase-rs = "2.1.1"
tokio = { version = "1", features = ["full"] }  
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }